---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "Viraat Aryabumi"
keywords:    "viraat, Viraat, Aryabumi, aryabumi, template, github, design, single page"
description: "Landing page of Viraat Aryabumi"
source_link: "https://github.com/t413/SinglePaged"
favicon:     "img/favicons/favicon.ico"
touch_icon:  "img/favicons/apple-touch-icon.png"
google_analytics_key: UA-58878965-1  ## put YOUR key here to enable tracking! (blank to disable)

gems:
  - octopress-minify-html

### template colors, used site-wide via css ###
colors:
  black:		'#2C2B29'
  white:		'#F3EDE1'
  briwhite: '#FFFFFF'
  warmgray1:		'#B8B8B8'
  warmgray2:		'#A4A4A4'
  warmgray3:		'#909090'
  gray1:    '#EFEFEF'
  gray2:    '#DEDEDE'
  gray3:    '#CDCDCD'
  red:      '#FF3636'
  blue:			'#49a7e9'
  green:		'#9bcf2f'
  purple:		'#c869bf'
  orange:		'#fab125'
  turquoise:	'#0fbfcf'
